Repository etendosoftware/docs, pull requests merged in 2024-07, with the labels that each got.

#223 Feature EM-329: Update ISO release notes
  docs/whats-new/release-notes/etendo-classic/iso.md
Labels: documentation

#225 Feature EM-329: Update livebuild versions
  docs/live-builds/overview.md
Labels: documentation

#207 Feature EPL-1548: Data model
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-1.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-11.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-12.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-13.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-14.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-15.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-17.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-18.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-19.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-2.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-21.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-22.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-3.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-4.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-5.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-6.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-7.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-8.png
  docs/assets/developer-guide/etendo-classic/concepts/Data_Model-9.png
  docs/developer-guide/etendo-classic/concepts/.Data_Model.md
  docs/developer-guide/etendo-classic/concepts/Data_Access_Layer.md
  docs/developer-guide/etendo-classic/concepts/data-model.md
  mkdocs.yml
Labels: documentation

#226 Feature EPL-1439: added relative path. removed: unused picture
  docs/assets/developer-guide/etendo-classic/how-to-guides/displaylogic.png
  docs/developer-guide/etendo-classic/how-to-guides/how-to-define-display-logic-evaluated-at-server-level.md
Labels: bug, documentation

#224 Feature EML-563: Copilot Installation page improvements
  docs/developer-guide/etendo-copilot/installation.md
Labels: documentation

#217 Feature EE-1016: Create Wiki documentation for VAT Regularization module
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization1.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization2.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization3.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization4.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization5.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization6.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization7.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/vatregularization8.png
  docs/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions.md
  docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/overview.md
Labels: documentation

#227 Hotfix EPL-1636: Incorrect Asset Paths in Wiki Pages
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_use_property_fields-6.png
  docs/developer-guide/etendo-classic/concepts/.javascript-coding-conventions.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-client-side-callout-onchange-function.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-use-property-fields.md
Labels: documentation

#213 Feature EPL-1507: Standard Windows
  docs/assets/developer-guide/etendo-classic/concepts/Standard_Windows-0.png
  docs/assets/developer-guide/etendo-classic/concepts/Standard_Windows-1.png
  docs/assets/developer-guide/etendo-classic/concepts/Standard_Windows-2.png
  docs/developer-guide/etendo-classic/concepts/.Standard_Windows.md
  docs/developer-guide/etendo-classic/concepts/standard-windows.md
  mkdocs.yml
Labels: documentation

#234 Feature EE-1058: Create VAT Regularization video tutorial
  docs/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions.md
  docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/overview.md
Labels: documentation

#231 Feature EPL-1675: How to create a HQL Based Table
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_HQL_Based_Table-1.png
  docs/developer-guide/etendo-classic/how-to-guides/.how-to-create-a-hql-based-table.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-a-hql-based-table.md
  mkdocs.yml
Labels: documentation

#236 Feature EML-586: Create Tool Pack documentation
  docs/developer-guide/etendo-classic/how-to-guides/How-to-Create-a-Chart-of-Accounts-Module.md
  docs/developer-guide/etendo-copilot/available-tools/attach-file-tool.md
  docs/developer-guide/etendo-copilot/available-tools/database-query-tool.md
  docs/developer-guide/etendo-copilot/available-tools/ddl-tool.md
  docs/developer-guide/etendo-copilot/available-tools/file-copy-tool.md
  docs/developer-guide/etendo-copilot/available-tools/file-downloader-tool.md
  docs/developer-guide/etendo-copilot/available-tools/ocr-tool.md
  docs/developer-guide/etendo-copilot/available-tools/openapi-tool.md
  docs/developer-guide/etendo-copilot/available-tools/overview.md
  docs/developer-guide/etendo-copilot/available-tools/pdf-to-images-tool.md
  docs/developer-guide/etendo-copilot/available-tools/print-directory-tool.md
  docs/developer-guide/etendo-copilot/available-tools/read-file-tool.md
  docs/developer-guide/etendo-copilot/available-tools/send-email-tool.md
  docs/developer-guide/etendo-copilot/available-tools/tavily-tool.md
  docs/developer-guide/etendo-copilot/available-tools/template-tool.md
  docs/developer-guide/etendo-copilot/available-tools/uncompress-tool.md
  docs/developer-guide/etendo-copilot/available-tools/write-file-tool.md
  docs/developer-guide/etendo-copilot/available-tools/xml-translation-tool.md
  docs/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions.md
  docs/user-guide/etendo-classic/basic-features/warehouse-management/analysis-tools.md
  docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/overview.md
  docs/user-guide/etendo-mobile/user-interface/user-interface.md
  mkdocs.yml
Labels: documentation

#235 Feature EML-596: Fixed documentation with new imports
  docs/developer-guide/etendo-copilot/how-to-create-copilot-tools.md
Labels: documentation

#240 Feature ETP-78: Add Etendo News for June
  docs/whats-new/release-notes/etendo-news.md
Labels: documentation

#237 Feature EPL-1631: How to Create a Callout that Extends from Another Callout
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_callout_that_extends_from_another_callout-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_callout_that_extends_from_another_callout-2.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_callout_that_extends_from_another_callout-3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_callout_that_extends_from_another_callout-4.png
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_create_a_callout_that_extends_from_another_callout.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-a-callout-that-extends-from-another-callout.md
  mkdocs.yml
Labels: documentation

#242 Feature ETP-78: Add Etendo News for July
  docs/developer-guide/etendo-copilot/bundles/create-references.md
  docs/developer-guide/etendo-copilot/bundles/dev-assistant.md
  docs/developer-guide/etendo-copilot/bundles/overview.md
  docs/whats-new/release-notes/etendo-news.md
  mkdocs.yml
Labels: documentation, release notes

#241 Feature EPL-1571: How To Change The Size of a Column
  docs/developer-guide/etendo-classic/how-to-guides/.How_To_Change_The_Size_of_a_Column.md
  docs/developer-guide/etendo-classic/how-to-guides/How_To_Create_a_Configuration_Script.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-change-the-size-of-a-column.md
  mkdocs.yml
Labels: documentation
