Repository etendosoftware/docs, pull requests merged in 2024-05, with the labels that each got.

#176 Hotfix EPL-1449: Add Know Issue and ISO link in RL
  docs/whats-new/release-notes/etendo-classic/known-issues.md
  docs/whats-new/release-notes/etendo-classic/release-notes.md
Labels: bug

#179 Hotfix EPL-1449: Fix code block type in know issue
  docs/whats-new/release-notes/etendo-classic/known-issues.md
Labels: bug

#178 Feature EPL-1465: Add ISO installation guide and release notes
  docs/getting-started/installation.md
  docs/whats-new/release-notes/etendo-classic/iso.md
  mkdocs.yml
Labels: enhancement

#181 Feature EPL-1459: Check and format the document
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_create_build_validations_and_module_scripts.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-build-validations-and-module-scripts.md
  mkdocs.yml
Labels: documentation

#182 Feature EPL-1470: Add Taxes, 303 and 390 fixes to migration doc
  docs/assets/whats-new/release-notes/etendo-clasic/known-issues/fix_localization_spain_303_2023_ids.sql
  docs/assets/whats-new/release-notes/etendo-clasic/known-issues/fix_localization_spain_390_2022_ids.sql
  docs/assets/whats-new/release-notes/etendo-clasic/known-issues/fix_taxes_ids_different_orgs.sql
  docs/assets/whats-new/release-notes/etendo-clasic/known-issues/fix_taxes_ids_same_org.sql
  docs/developer-guide/etendo-classic/getting-started/migration-from-openbravo/migrating-to-etendo-from-openbravo.md
  docs/whats-new/release-notes/etendo-classic/known-issues.md
Labels: documentation

#189 Feature EPL-1454: How to create a pick and execute process
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-10.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-11.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-12.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-14.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-15.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-17.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-18.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-19.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-2.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-20.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-21.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-22.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-23.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-24.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-25.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-26.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-27.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-28.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-4.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-5.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-6.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-7.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-8.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Pick_and_Execute_Process-9.png
  docs/developer-guide/etendo-classic/how-to-guides/.how-to-create-a-hql-based-table.md
  docs/developer-guide/etendo-classic/how-to-guides/.how-to-create-a-table-based-on-a-user-defined-datasource.md
  docs/developer-guide/etendo-classic/how-to-guides/.how-to-create-client-event-handler-actions.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-add-a-field-to-a-window-tab.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-a-pick-and-execute-process.md
  mkdocs.yml
Labels: documentation

#190 Feature EML-524: Added SQL Assistant documentation and webhooks enabl…
  docs/assets/developer-guide/etendo-copilot/available-tools/database-query-tool-2.png
  docs/assets/developer-guide/etendo-copilot/available-tools/database-query-tool-3.png
  docs/assets/developer-guide/etendo-copilot/available-tools/database-query-tool.png
  docs/assets/user-guide/etendo-copilot/bundles/sql-expert/sql-assistant-2.png
  docs/assets/user-guide/etendo-copilot/bundles/sql-expert/sql-assistant-3.png
  docs/assets/user-guide/etendo-copilot/bundles/sql-expert/sql-assistant-4.png
  docs/assets/user-guide/etendo-copilot/bundles/sql-expert/sql-assistant-5.png
  docs/assets/user-guide/etendo-copilot/bundles/sql-expert/sql-assistant.png
  docs/developer-guide/etendo-copilot/available-tools/database-query-tool.md
  docs/developer-guide/etendo-copilot/installation.md
  docs/user-guide/etendo-copilot/bundles/overview.md
  docs/user-guide/etendo-copilot/bundles/sql-expert.md
  docs/user-guide/etendo-copilot/setup.md
  mkdocs.yml
Labels: documentation

#198 Feature EPL-1459: Deleted unnecessary images and update the first one.
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_build_validations_and_module_scripts-0.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_build_validations_and_module_scripts-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_build_validations_and_module_scripts-3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_build_validations_and_module_scripts-5.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_build_validations_and_module_scripts-7.png
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-build-validations-and-module-scripts.md
Labels: documentation

#199 Hotfix EPL-1523: Replace wrong URLs
  docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_rich_text_field_and_column.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_change_an_existing_Window.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-add-a-field-to-a-window-tab.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-add-columns-to-a-table.md
  mkdocs.yml
Labels: documentation

#184 Feature EML-521: Create Dev Assistant Technical Documentation
  docs/assets/developer-guide/etendo-copilot/available-tools/ddl-tool/ddl-tool.png
  docs/assets/developer-guide/etendo-copilot/available-tools/ddl-tool/ddl-tool1.png
  docs/assets/user-guide/etendo-copilot/bundles/dev-assistant/dev-assistant.png
  docs/assets/user-guide/etendo-copilot/bundles/dev-assistant/dev-assistant1.png
  docs/assets/user-guide/etendo-copilot/bundles/dev-assistant/dev-assistant2.png
  docs/assets/user-guide/etendo-copilot/bundles/dev-assistant/dev-assistant3.png
  docs/assets/user-guide/etendo-copilot/bundles/dev-assistant/dev-assistant4.png
  docs/developer-guide/etendo-copilot/available-tools/ddl-tool.md
  docs/user-guide/etendo-copilot/bundles/dev-assistant.md
  mkdocs.yml
Labels: documentation
