Repository etendosoftware/docs, pull requests merged in 2024-03, with the labels that each got.

#121 Feature EE-626: Add Release Notes for Platform ES Extensions
  docs/whats-new/release-notes/etendo-classic/translation-bundles/platform-extensions-es_es/release-notes.md
Labels: documentation

#126 Hotfix EPL-1274: Refactoring of Etendo Backup & Restore documentation
  docs/developer-guide/etendo-classic/developer-tools/etendo-backup-restore-tool.md
  docs/whats-new/release-notes/etendo-classic/plugins/etendo-backup-restore-plugin/release-notes.md
  docs/whats-new/release-notes/etendo-classic/plugins/etendo-gradle-plugin/release-notes.md
  mkdocs.yml
Labels: bug, documentation, enhancement

#127 Hotfix EE-768: Fix Purchase Invoice SII registration documentation
  docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/sii-para-iva.md
Labels: bug, documentation

#128 EPL-1288 [Concepts] How to Create a Window
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window-10.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window-11.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window-9.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_0.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_10.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_2.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_4.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_5.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_6.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_7.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_8.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_Create_a_Window_9.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_window--5.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/how_to_create_a_window--3.png
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_create_a_Window.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Window.md
  mkdocs.yml
Labels: documentation

#130 Feature ETO-284: Add links github releases bundles
  docs/whats-new/release-notes/etendo-classic/bundles/essentials-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/etendobi-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/financial-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/localization-spain-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/platform-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/procurement-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/production-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/sales-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/bundles/warehouse-extensions/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/essentials-extensions-es_es/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/etendobi-extensions-es_es/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/financial-extensions-es_es/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/platform-extensions-es_es/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/procurement-extensions-es_es/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/production-extensions-es_es/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/sales-extensions-es_es/release-notes.md
  docs/whats-new/release-notes/etendo-classic/translation-bundles/warehouse-extensions-es_es/release-notes.md
Labels: documentation, enhancement

#134 Feature EPL-1296: Add how to create jest testcases page
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_create_Jest_testcases.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-jest-testcases.md
  mkdocs.yml
Labels: documentation

#141 Feature EPL-1297: Add how-to junit testcases page
  docs/assets/developer-guide/etendo-classic/how-to-guides/how-to-create-junit-testcases/how-to-create-junit-testcases-6.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/how-to-create-junit-testcases/how-to-create-junit-testcases-7.png
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_create_JUnit_testcases.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-junit-testcases.md
  mkdocs.yml
Labels: documentation

#144 Feature EPL-1261: Reordering '[How-to] create testcases' pages
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-testcases/how-to-create-jest-testcases.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-testcases/how-to-create-junit-testcases.md
  mkdocs.yml
Labels: documentation

#145 Feature EPL-1298: Remove '[How to] create QUnit test cases' page
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_create_QUnit_testcases.md
  mkdocs.yml
Labels: documentation

#143 EPL-1339 - [How To] How to implement a business event handler
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_implement_a_business_event_handler-0.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_implement_a_business_event_handler-3.png
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_implement_a_business_event_handler.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_implement_a_business_event_handler.md
  mkdocs.yml
Labels: documentation

#147 Feature EPL-1261: Add tags in '[How-to] create testcases' pages
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-testcases/how-to-create-jest-testcases.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-create-testcases/how-to-create-junit-testcases.md
  mkdocs.yml
Labels: documentation

#138 EPL-1302: [How-to] How to add a canvas field to a Form or Grid
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-0.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-2.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid-3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/com.etendoerp.client.application.examples.zip
  docs/developer-guide/etendo-classic/concepts/.Client_Side_Development_and_API.md
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_add_a_canvas_field_to_a_Form_or_Grid.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_canvas_field_to_a_Form_or_Grid.md
  mkdocs.yml
Labels: documentation

#140 EPL-1292: How to create a Report
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-10.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-11.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-12.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-13.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-14.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-15.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-16.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-19.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-20.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-21.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-22.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-23.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-24.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-25.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-26.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-4.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-5.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-6.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-7.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-8.png
  docs/assets/developer-guide/etendo-classic/concepts/How_to_create_a_Report-9.png
  docs/assets/developer-guide/etendo-classic/concepts/Utility.jar
  docs/assets/developer-guide/etendo-classic/how-to-guides/Barcodes.jrxml
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-10.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-11.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-12.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-13.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-14.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-15.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-16.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-19.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-2.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-20.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-21.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-22.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-23.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-24.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-25.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-26.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-4.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-5.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-6.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-7.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-8.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report-9.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/org.openbravo.service.reporting.barcode.zip
  docs/developer-guide/etendo-classic/concepts/.How_to_create_a_Report.md
  docs/developer-guide/etendo-classic/how-to-guides/.How_to_create_a_Report.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Report.md
  mkdocs.yml
Labels: documentation

#135 EPL-1344 Migrate article to wiki: Processes
  docs/assets/developer-guide/etendo-classic/concepts/Processes-0.png
  docs/assets/developer-guide/etendo-classic/concepts/Processes-1.png
  docs/developer-guide/etendo-classic/concepts/.Processes.md
  docs/developer-guide/etendo-classic/concepts/Processes.md
  mkdocs.yml
Labels: documentation

#132 EPL-1338: Add "How to Create a Module"
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_a_Module-0.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_a_Module-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_a_Module-2.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_a_Module-3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_and_Package_a_Module-0.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_and_Package_a_Module-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_and_Package_a_Module-3.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_and_Package_a_Module-4.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_and_Package_a_Module-6.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_and_Package_a_Module-7.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_To_Create_and_Package_a_Module-8.png
  docs/developer-guide/etendo-classic/how-to-guides/.How_To_Create_and_Package_a_Module.md
  docs/developer-guide/etendo-classic/how-to-guides/How_To_Create_a_Module.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_an_Alert.md
  mkdocs.yml
Labels: documentation

#146 Feature EPL-1412: Alphabetize the How to guides and Concepts sections
  docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_field_to_a_Window_Tab.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_add_a_rich_text_field_and_column.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_change_an_existing_Window.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Background_Process.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Callout.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Dataset.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_a_Window.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_create_an_Alert.md
  docs/developer-guide/etendo-classic/how-to-guides/how-to-add-a-button-to-the-toolbar.md
  mkdocs.yml
Labels: documentation

#149 Feature EPL-1403: How to create a Chart of Accounts Module
  docs/assets/developer-guide/etendo-classic/how-to-guides/COA.csv
  docs/assets/developer-guide/etendo-classic/how-to-guides/CSVfile.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/CSVfile_Export.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/chartofaccountsics.png
  docs/developer-guide/etendo-classic/how-to-guides/How-to-Create-Accounts-Files.md
  docs/developer-guide/etendo-classic/how-to-guides/How-to-Create-a-Chart-of-Accounts-Module.md
  mkdocs.yml
Labels: documentation

#150 Feature EPL-1361: Initial client setup
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_run_an_initial_client_setup_process-1.png
  docs/assets/developer-guide/etendo-classic/how-to-guides/How_to_run_an_initial_client_setup_process-2.png
  docs/developer-guide/etendo-classic/concepts/Datasets.md
  docs/developer-guide/etendo-classic/how-to-guides/How_to_run_an_initial_client_setup_process.md
  docs/user-guide/etendo-classic/basic-features/financial-management/accounting/setup.md
  docs/user-guide/etendo-classic/basic-features/general-setup/client.md
  docs/user-guide/etendo-classic/basic-features/general-setup/enterprise-model.md
  docs/user-guide/etendo-classic/basic-features/general-setup/getting-started.md
  docs/user-guide/etendo-classic/basic-features/general-setup/security.md
  mkdocs.yml
Labels: documentation
