Repository etendosoftware/docs, pull requests merged in 2024-01, with the labels that each got.

#57 Feature ETO-271: automated deployment & versioning
  .github/actions/setup-docs/action.yml
  .github/workflows/deploy.yml
  README.md
  docs/.github/workflows/ci.yml
Labels: enhancement

#64 Feature ETO-273: Add to a pipeline the exec of compile_docs.py and commit it
  .github/workflows/ci.yml
  .github/workflows/compile-docs.yml
  compile_docs.py
Labels: documentation, enhancement

#68 Feature EE-704: Create release notes for Platform Extensions ES bundle
  docs/whats-new/release-notes/etendo-classic/translation-bundles/platform-extensions-es/release-notes.md
  mkdocs.yml
Labels: documentation

#67 Feature EE-705: Add Essentials Extensions ES release notes page
  docs/whats-new/release-notes/etendo-classic/translation-bundles/essentials-extensions-es/release-notes.md
  mkdocs.yml
Labels: documentation

#76 Feature EE-701: Create release notes for Sales Extensions ES bundle
  docs/whats-new/release-notes/etendo-classic/translation-bundles/sales-extensions-es/release-notes.md
  mkdocs.yml
Labels: documentation

#74 Feature EE-703: Create rel. notes for Production Extensions ES bundle
  docs/whats-new/release-notes/etendo-classic/translation-bundles/production-extensions-es/release-notes.md
  mkdocs.yml
Labels: documentation

#77 Feature EE-707: Create release notes page for Etendo BI Extensions bundle
  docs/whats-new/release-notes/etendo-classic/translation-bundles/etendobi-extensions-es/release-notes.md
  mkdocs.yml
Labels: documentation

#78 Feature EE-706: Add release notes page for Warehouse Extensions bundle
  docs/whats-new/release-notes/etendo-classic/translation-bundles/warehouse-extensions-es/release-notes.md
  mkdocs.yml
Labels: documentation

#82 Feature EML-440: Added examples for Copilot Tools with multiple params
  README.md
  docs/developer-guide/etendo-copilot/how-to-create-copilot-tools.md
Labels: documentation

#63 Feature EE-301: Add new SII status to docs
  docs/user-guide/etendo-classic/optional-features/bundles/spain-localization/sii-para-iva.md
Labels: documentation

#84 Feature EE-748: Add release notes for modules added to bundle
  docs/whats-new/release-notes/etendo-classic/translation-bundles/financial-extensions-es/release-notes.md
Labels: documentation

#85 Feature EE-770: Add Release Notes for Localization Spain Ext. v1.7.0
  docs/whats-new/release-notes/etendo-classic/bundles/spain-localization/release-notes.md
Labels: documentation

#86 Feature ETO-271: Check commit name & skip steps
  .github/workflows/deploy-docs.yml
Labels: enhancement

#89 Feature EE-789: Add release notes for Localization Spain Ext. v1.8.0
  docs/whats-new/release-notes/etendo-classic/bundles/localization-spain-extensions/release-notes.md
Labels: documentation
