Repository etendosoftware/docs, pull requests merged in 2025-01, with the labels that each got.

#312 Feature ETP-587: Wiki Documentation for com.etendoerp.automated.warehouse.reservation module
  docs/user-guide/etendo-classic/basic-features/sales-management/transactions.md
  docs/user-guide/etendo-classic/basic-features/warehouse-management/transactions.md
  docs/user-guide/etendo-classic/optional-features/bundles/warehouse-extensions/overview.md
Labels: documentation

#313 Feature ETP-697: Add December Etendo news
  docs/assets/whats-new/etendo-news/automated-remittances.png
  docs/assets/whats-new/etendo-news/bulk-completion.png
  docs/whats-new/release-notes/etendo-news.md
Labels: documentation

#314 Feature ETP-589: Wiki Documentation for Bank Account in Payment Plan module
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba1.png
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba2.png
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba3.png
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba4.png
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba5.png
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba6.png
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba7.png
  docs/assets/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management/aba8.png
  docs/user-guide/etendo-classic/basic-features/financial-management/receivables-and-payables/transactions.md
  docs/user-guide/etendo-classic/basic-features/master-data-management/master-data.md
  docs/user-guide/etendo-classic/basic-features/procurement-management/transactions.md
  docs/user-guide/etendo-classic/basic-features/sales-management/transactions.md
  docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/advanced-bank-account-management.md
  docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/overview.md
  mkdocs.yml
Labels: documentation

#315 Feature ETP-943: Add Debug Log section
  docs/assets/developer-guide/etendo-mobile/tutorials/create-new-subapplication/rx-config-auth.png
  docs/assets/developer-guide/etendo-mobile/tutorials/create-new-subapplication/rx-config-config.png
  docs/assets/developer-guide/etendo-mobile/tutorials/create-new-subapplication/rx-config.png
  docs/developer-guide/etendo-mobile/tutorials/create-new-subapplication.md
Labels: documentation

#324 Feature ETP-964: Refactor Mobile Extensions documentation
  docs/user-guide/etendo-copilot/bundles/overview.md
  docs/user-guide/etendo-mobile/bundles/mobile-extensions/etendo-classic-subapp.md
  docs/user-guide/etendo-mobile/bundles/mobile-extensions/overview.md
  docs/user-guide/etendo-mobile/getting-started.md
  docs/user-guide/etendo-mobile/user-interface/user-interface.md
  docs/whats-new/release-notes/etendo-mobile/bundles/mobile-extensions/release-notes.md
  mkdocs.yml
Labels: documentation

#319 Hotfix ETP-880: Fix documentation about BI Connector module
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-0.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-1.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-10.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-11.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-12.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-13.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-2.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-3.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-4.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-5.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-6.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-7.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-8.png
  docs/assets/developer-guide/etendo-classic/bundles/etendo-bi/etendo-bi-connector-9.png
  docs/assets/drive/1J07aRNJeYl5QsU0z6Q95m2lT-hAp6FrC.png
  docs/assets/drive/Bl15uB38OKLSH0-MZwACXtCP4Jzz7uvYLqwRMJVv_Fc5n9aknGQN7SoMEDwGvo-nZ56ShJxB3gJ6xT_4CGpVNMdlph3rSUB1z6J7tpYmVBF5T7xHqo9VBdNrR8OGLrzR4nJU0ob85tLZcdINBrPF2Ek.png
  docs/developer-guide/etendo-classic/bundles/etendo-bi-bundle.md
  docs/developer-guide/etendo-classic/bundles/etendo-bi-extensions.md
  docs/user-guide/etendo-classic/optional-features/bundles/etendobi-extensions/etendo-bi-connector.md
  docs/user-guide/etendo-classic/optional-features/bundles/etendobi-extensions/inclusion-exclusion-configuration.md
  docs/user-guide/etendo-classic/optional-features/bundles/etendobi-extensions/overview.md
  mkdocs.yml
Labels: enhancement

#327 Hotfix ETP-323: Fix documentation of backup plugin
  docs/developer-guide/etendo-classic/developer-tools/etendo-backup-restore-tool.md
Labels: bug

#331 Feature ETP-1112: Add january Etendo news
  docs/assets/whats-new/etendo-news/advanced-bank-account.png
  docs/assets/whats-new/etendo-news/attach-multiple-files-copilot.png
  docs/assets/whats-new/etendo-news/automatic-warehouse-reservation.png
  docs/whats-new/etendo-news.md
  docs/whats-new/release-notes/etendo-classic/plugins/etendo-backup-restore-plugin/release-notes.md
Labels: documentation

#332 Feature ETP-821: Wiki Documentation for Non-Posted Documents Feature module
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/not-posted-documents.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/not-posted-documents2.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/not-posted-documents3.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/not-posted-documents4.png
  docs/assets/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions/not-posted-documents5.png
  docs/user-guide/etendo-classic/basic-features/financial-management/accounting/transactions.md
  docs/user-guide/etendo-classic/optional-features/bundles/financial-extensions/bulk-posting.md
Labels: documentation
